# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X eksdemo/cmd.version={{ .Version }} -X eksdemo/cmd.commit={{ .ShortCommit }} -X eksdemo/cmd.date={{ .Date }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
brews:
  - name: eksdemo
    tap:
      owner: aaroniscode
      name: homebrew-tap
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/aaroniscode/eksdemo"
    description: "A toolkit to quickly and easily demo EKS with opinioned application installs."
    license: "MIT"
    dependencies:
      - name: weaveworks/tap/eksctl

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
